export const title = "Layer cake for birthdays";
export const reviews = [
  {
    username: "@Bahdja_mesers",
    userPicture: "/images/cardseller.png",
    title: "Produit excellent mais long a arriver",
    description:
      "Sed interdum ut scelerisque lectus dui diam semper massa scelerisque. Elit amet quis at rhoncus aliquet dui pretium ut. In ac ut enim sed ultrices.",
    rating: 4,
    date: "13/07/2023",
  },
  {
    username: "@Bahdja_mesers",
    userPicture: "/images/cardseller.png",
    title: "Produit excellent mais long a arriver",
    description:
      "Sed interdum ut scelerisque lectus dui diam semper massa scelerisque. Elit amet quis at rhoncus aliquet dui pretium ut. In ac ut enim sed ultrices.",
    rating: 4,
    date: "13/07/2023",
  },
  {
    username: "@Bahdja_mesers",
    userPicture: "/images/cardseller.png",
    title: "Produit excellent mais long a arriver",
    description:
      "Sed interdum ut scelerisque lectus dui diam semper massa scelerisque. Elit amet quis at rhoncus aliquet dui pretium ut. In ac ut enim sed ultrices.",
    rating: 4,
    date: "13/07/2023",
  },
  {
    username: "@Bahdja_mesers",
    userPicture: "/images/cardseller.png",
    title: "Produit excellent mais long a arriver",
    description:
      "Sed interdum ut scelerisque lectus dui diam semper massa scelerisque. Elit amet quis at rhoncus aliquet dui pretium ut. In ac ut enim sed ultrices.",
    rating: 4,
    date: "13/07/2023",
  },
  {
    username: "@Bahdja_mesers",
    userPicture: "/images/cardseller.png",
    title: "Produit excellent mais long a arriver",
    description:
      "Sed interdum ut scelerisque lectus dui diam semper massa scelerisque. Elit amet quis at rhoncus aliquet dui pretium ut. In ac ut enim sed ultrices.",
    rating: 4,
    date: "13/07/2023",
  },
  {
    username: "@Bahdja_mesers",
    userPicture: "/images/cardseller.png",
    title: "Produit excellent mais long a arriver",
    description:
      "Sed interdum ut scelerisque lectus dui diam semper massa scelerisque. Elit amet quis at rhoncus aliquet dui pretium ut. In ac ut enim sed ultrices.",
    rating: 4,
    date: "13/07/2023",
  },
  {
    username: "@Bahdja_mesers",
    userPicture: "/images/cardseller.png",
    title: "Produit excellent mais long a arriver",
    description:
      "Sed interdum ut scelerisque lectus dui diam semper massa scelerisque. Elit amet quis at rhoncus aliquet dui pretium ut. In ac ut enim sed ultrices.",
    rating: 4,
    date: "13/07/2023",
  },
  {
    username: "@Bahdja_mesers",
    userPicture: "/images/cardseller.png",
    title: "Produit excellent mais long a arriver",
    description:
      "Sed interdum ut scelerisque lectus dui diam semper massa scelerisque. Elit amet quis at rhoncus aliquet dui pretium ut. In ac ut enim sed ultrices.",
    rating: 4,
    date: "13/07/2023",
  },
  {
    username: "@notme",
    userPicture: "/images/cardseller.png",
    title: "Produit excellent mais long a arriver",
    description:
      "Sed interdum ut scelerisque lectus dui diam semper massa scelerisque. Elit amet quis at rhoncus aliquet dui pretium ut. In ac ut enim sed ultrices.",
    rating: 4,
    date: "13/07/2023",
  },
];

export const item = {
  itemUrl: "/images/carditem.png",
  sellerUrl: "/images/cardseller.png",
  title: "Layer Cake for birthdays",
  salePrice: "100000.00",
  isOnSale: true,
  isLiked: false,
  images: [],
  description:
    "Lorem ipsum dolor sit amet consectetur. Mattis sed sodales urna nisl facilisi egestas. Congue tortor auctor lectus auctor dolor aenean egestas vel. Et id nunc nisl nulla.",
  location: "Bejaia",
  phoneNumber: "+2135 78 83 29 33",
  seller: "SweetyPie",
};

export const ratings = {
  1: 328,
  2: 321,
  3: 98,
  4: 50,
  5: 28,
};

export const products = [
  {
    itemUrl: "/images/carditem.png",
    sellerUrl: "/images/cardseller.png",
    title: "Random Product",
    basePrice: "1000",
    salePrice: "999",
    isOnSale: true,
    isLiked: true,
    seller: "Anonymous",
  },
  {
    itemUrl: "/images/carditem.png",
    sellerUrl: "/images/cardseller.png",
    title: "Random Product",
    basePrice: "1000",
    salePrice: "999",
    isOnSale: true,
    isLiked: true,
    seller: "Anonymous",
  },
  {
    itemUrl: "/images/carditem.png",
    sellerUrl: "/images/cardseller.png",
    title: "Random Product",
    basePrice: "1000",
    salePrice: "999",
    isOnSale: true,
    isLiked: true,
    seller: "Anonymous",
  },
  {
    itemUrl: "/images/carditem.png",
    sellerUrl: "/images/cardseller.png",
    title: "Random Product",
    basePrice: "1000",
    salePrice: "999",
    isOnSale: true,
    isLiked: true,
    seller: "Anonymous",
  },
  {
    itemUrl: "/images/carditem.png",
    sellerUrl: "/images/cardseller.png",
    title: "Random Product",
    basePrice: "1000",
    salePrice: "999",
    isOnSale: true,
    isLiked: true,
    seller: "Anonymous",
  },
  {
    itemUrl: "/images/carditem.png",
    sellerUrl: "/images/cardseller.png",
    title: "Random Product",
    basePrice: "1000",
    salePrice: "999",
    isOnSale: true,
    isLiked: true,
    seller: "Anonymous",
  },
  {
    itemUrl: "/images/carditem.png",
    sellerUrl: "/images/cardseller.png",
    title: "Random Product",
    basePrice: "1000",
    salePrice: "999",
    isOnSale: true,
    isLiked: true,
    seller: "Anonymous",
  },
  {
    itemUrl: "/images/carditem.png",
    sellerUrl: "/images/cardseller.png",
    title: "Random Product",
    basePrice: "1000",
    salePrice: "999",
    isOnSale: true,
    isLiked: true,
    seller: "Anonymous",
  },
  {
    itemUrl: "/images/carditem.png",
    sellerUrl: "/images/cardseller.png",
    title: "Random Product",
    basePrice: "1000",
    salePrice: "999",
    isOnSale: true,
    isLiked: true,
    seller: "Anonymous",
  },
  {
    itemUrl: "/images/carditem.png",
    sellerUrl: "/images/cardseller.png",
    title: "Random Product",
    basePrice: "1000",
    salePrice: "999",
    isOnSale: true,
    isLiked: true,
    seller: "Anonymous",
  },
  {
    itemUrl: "/images/carditem.png",
    sellerUrl: "/images/cardseller.png",
    title: "Random Product",
    basePrice: "1000",
    salePrice: "999",
    isOnSale: true,
    isLiked: true,
    seller: "Anonymous",
  },
  {
    itemUrl: "/images/carditem.png",
    sellerUrl: "/images/cardseller.png",
    title: "Random Product",
    basePrice: "1000",
    salePrice: "999",
    isOnSale: true,
    isLiked: true,
    seller: "Anonymous",
  },
  {
    itemUrl: "/images/carditem.png",
    sellerUrl: "/images/cardseller.png",
    title: "Random Product",
    basePrice: "1000",
    salePrice: "999",
    isOnSale: true,
    isLiked: true,
    seller: "Now you see me",
  },
];
