const data = [
  {
    imageURL: "/images/lyes.jpeg",
    userName: "Lyes",
    email: "lyes@ensia.dz",
    location: "Tizi Ouzou",
    phoneNumber: "+2135555555555",
    rating: 5,
    minPrice: 200,
    maxPrice: 999,
    products: [
      {
        itemUrl: "/images/carditem.png",
        sellerUrl: "/images/cardseller.png",
        title: "Random Product",
        basePrice: "1000",
        salePrice: "999",
        isOnSale: true,
        isLiked: true,
        seller: "Anonymous",
      },
      {
        itemUrl: "/images/carditem.png",
        sellerUrl: "/images/cardseller.png",
        title: "Random Product",
        basePrice: "1000",
        salePrice: "999",
        isOnSale: true,
        isLiked: true,
        seller: "Anonymous",
      },
      {
        itemUrl: "/images/carditem.png",
        sellerUrl: "/images/cardseller.png",
        title: "Random Product",
        basePrice: "1000",
        salePrice: "999",
        isOnSale: true,
        isLiked: true,
        seller: "Anonymous",
      },
      {
        itemUrl: "/images/carditem.png",
        sellerUrl: "/images/cardseller.png",
        title: "Random Product",
        basePrice: "1000",
        salePrice: "999",
        isOnSale: true,
        isLiked: true,
        seller: "Anonymous",
      },
      {
        itemUrl: "/images/carditem.png",
        sellerUrl: "/images/cardseller.png",
        title: "Random Product",
        basePrice: "1000",
        salePrice: "999",
        isOnSale: true,
        isLiked: true,
        seller: "Anonymous",
      },
      {
        itemUrl: "/images/carditem.png",
        sellerUrl: "/images/cardseller.png",
        title: "Random Product",
        basePrice: "1000",
        salePrice: "999",
        isOnSale: true,
        isLiked: true,
        seller: "Anonymous",
      },
      {
        itemUrl: "/images/carditem.png",
        sellerUrl: "/images/cardseller.png",
        title: "Random Product",
        basePrice: "1000",
        salePrice: "999",
        isOnSale: true,
        isLiked: true,
        seller: "Anonymous",
      },
      {
        itemUrl: "/images/carditem.png",
        sellerUrl: "/images/cardseller.png",
        title: "Random Product",
        basePrice: "1000",
        salePrice: "999",
        isOnSale: true,
        isLiked: true,
        seller: "Anonymous",
      },
      {
        itemUrl: "/images/carditem.png",
        sellerUrl: "/images/cardseller.png",
        title: "Random Product",
        basePrice: "1000",
        salePrice: "999",
        isOnSale: true,
        isLiked: true,
        seller: "Anonymous",
      },
      {
        itemUrl: "/images/carditem.png",
        sellerUrl: "/images/cardseller.png",
        title: "Random Product",
        basePrice: "1000",
        salePrice: "999",
        isOnSale: true,
        isLiked: true,
        seller: "Anonymous",
      },
      {
        itemUrl: "/images/carditem.png",
        sellerUrl: "/images/cardseller.png",
        title: "Random Product",
        basePrice: "1000",
        salePrice: "999",
        isOnSale: true,
        isLiked: true,
        seller: "Anonymous",
      },
      {
        itemUrl: "/images/carditem.png",
        sellerUrl: "/images/cardseller.png",
        title: "Random Product",
        basePrice: "1000",
        salePrice: "999",
        isOnSale: true,
        isLiked: true,
        seller: "Anonymous",
      },
      {
        itemUrl: "/images/carditem.png",
        sellerUrl: "/images/cardseller.png",
        title: "Random Product",
        basePrice: "1000",
        salePrice: "999",
        isOnSale: true,
        isLiked: true,
        seller: "Now you see me",
      },
    ],
    sales: [
      { x: "Sunday", sales: Math.floor(Math.random() * 10) },
      { x: "Monday", sales: Math.floor(Math.random() * 10) },
      { x: "Tuesday", sales: Math.floor(Math.random() * 10) },
      { x: "Wednesday", sales: Math.floor(Math.random() * 10) },
      { x: "Thursday", sales: Math.floor(Math.random() * 10) },
      { x: "Friday", sales: Math.floor(Math.random() * 10) },
      { x: "Saturday", sales: Math.floor(Math.random() * 10) },
    ],

    profit: [
      { x: "Sunday", profit: Math.floor(Math.random() * 10), unit: "DZD" },
      { x: "Monday", profit: Math.floor(Math.random() * 10), unit: "DZD" },
      { x: "Tuesday", profit: Math.floor(Math.random() * 10), unit: "DZD" },
      { x: "Wednesday", profit: Math.floor(Math.random() * 10), unit: "DZD" },
      { x: "Thursday", profit: Math.floor(Math.random() * 10), unit: "DZD" },
      { x: "Friday", profit: Math.floor(Math.random() * 10), unit: "DZD" },
      { x: "Saturday", profit: Math.floor(Math.random() * 10), unit: "DZD" },
    ],

    bestSeller: [
      { x: "Chocolate Cake", bestSeller: Math.floor(Math.random() * 10), unit: "DZD" },
      { x: "Cheese Cake", bestSeller: Math.floor(Math.random() * 10), unit: "DZD" },
      { x: "Strawberry Cake", bestSeller: Math.floor(Math.random() * 10), unit: "DZD" },
      { x: "Tiramissu", bestSeller: Math.floor(Math.random() * 10), unit: "DZD" },
    ],
  },
];

export default data;
